// APCs
class CUP_I_BTR80_ION: CUP_BTR80_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_BTR80A_ION: CUP_BTR80A_Base {
    MACRO_HIDE_VEHICLE;
};

// Cars
class CUP_I_Tigr_M_233114_PK_ION_WIN: CUP_Tigr_233114_PK_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_SUV_Armored_ION: CUP_SUV_Armored_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_FENNEK_ION: MRAP_03_base_F {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_FENNEK_GMG_ION: MRAP_03_gmg_base_F {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_FENNEK_HMG_ION: MRAP_03_hmg_base_F {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_MATV_ION: B_MRAP_01_F {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_MATV_GMG_ION: B_MRAP_01_gmg_F {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_MATV_HMG_ION: B_MRAP_01_hmg_F {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1025_M2_ION: CUP_nM1025_M2_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1025_M2_DF_ION: CUP_nM1025_M2_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1025_M240_DF_ION: CUP_nM1025_M240_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1025_Mk19_ION: CUP_nM1025_Mk19_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1025_Mk19_DF_ION: CUP_nM1025_Mk19_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1025_Unarmed_ION: CUP_nM1025_Unarmed_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1025_Unarmed_DF_ION: CUP_nM1025_Unarmed_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1025_SOV_M2_ION: CUP_nM1025_SOV_M2_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1035_amb_ION: CUP_nM1035_amb_BASE {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1025_SOV_Mk19_ION: CUP_nM1025_SOV_Mk19_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1035_amb_DF_ION: CUP_nM1035_amb_DF_BASE {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1036_TOW_ION: CUP_nM1036_TOW_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1036_TOW_DF_ION: CUP_nM1036_TOW_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1037sc_ION: CUP_nM1037sc_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1037sc_DF_ION: CUP_nM1037sc_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1038_ION: CUP_nM1038_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1038_DF_ION: CUP_nM1038_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1038_4s_ION: CUP_nM1038_4s_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1038_4s_DF_ION: CUP_nM1038_4s_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1038_Ammo_ION: CUP_nM1038_Ammo_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1038_Ammo_DF_ION: CUP_nM1038_Ammo_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1038_Repair_ION: CUP_nM1038_Repair_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1038_Repair_DF_ION: CUP_nM1038_Repair_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1151_crowslp_m2_ION: CUP_ECVHMMWV_crowslp_m2_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1151_crowslp_m2_DF_ION: CUP_ECVHMMWV_crowslp_m2_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1151_ogpk_m2_ION: CUP_ECVHMMWV_ogpk_m2_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1151_ogpk_m2_DF_ION: CUP_ECVHMMWV_ogpk_m2_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1151_ogpk_m240_ION: CUP_ECVHMMWV_ogpk_m240_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1151_ogpk_m240_DF_ION: CUP_ECVHMMWV_ogpk_m240_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1151_ogpk_mk19_DF_ION: CUP_ECVHMMWV_ogpk_mk19_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1151_ogpk_mk19_ION: CUP_ECVHMMWV_ogpk_mk19_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1151_Unarmed_ION: CUP_ECVHMMWV_Unarmed_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1151_Unarmed_DF_ION: CUP_ECVHMMWV_Unarmed_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_4WD_unarmed_ION: I_C_Offroad_02_unarmed_F {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_4WD_AT_ION: I_C_Offroad_02_AT_F {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_4WD_LMG_ION: I_C_Offroad_02_LMG_F {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_Pickup_Unarmed_PMC: CUP_Pickup_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_LSV_02_AT_ION: O_T_LSV_02_AT_F {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_LSV_02_Minigun_ION: O_LSV_02_armed_F {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_LSV_02_unarmed_ION: O_LSV_02_unarmed_F {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_RG31_Mk19_ION: CUP_RG31_Mk19 {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_RG31E_M2_ION: CUP_RG31E_M2 {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_RG31_M2_ION: CUP_RG31_M2 {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_RG31_M2_GC_ION: CUP_RG31_M2_GC {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_Tigr_M_233114_ION: CUP_Tigr_233114_u_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_SUV_ION: CUP_SUV_Unarmed_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_Tigr_M_233114_KORD_ION: CUP_Tigr_233114_KORD_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_Tigr_M_233114_PK_ION: CUP_Tigr_233114_PK_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_TowingTractor_ION: CUP_TowingTractor_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_Van_Cargo_ION: Van_02_vehicle_base_F {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_Van_ammo_ION: CUP_I_Van_Cargo_ION {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_Van_Repair_ION: CUP_I_Van_Cargo_ION {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_Van_Transport_ION: Van_02_transport_base_F {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1025_M2_ION_WIN: CUP_nM1025_M2_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1025_M2_DF_ION_WIN: CUP_nM1025_M2_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1025_M240_ION_WIN: CUP_nM1025_M240_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1025_M240_DF_ION_WIN: CUP_nM1025_M240_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1025_Mk19_ION_WIN: CUP_nM1025_Mk19_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1025_Mk19_DF_ION_WIN: CUP_nM1025_Mk19_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1025_Unarmed_ION_WIN: CUP_nM1025_Unarmed_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1025_Unarmed_DF_ION_WIN: CUP_nM1025_Unarmed_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1025_SOV_M2_ION_WIN: CUP_nM1025_SOV_M2_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1025_SOV_Mk19_ION_WIN: CUP_nM1025_SOV_Mk19_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1035_amb_ION_WIN: CUP_nM1035_amb_BASE {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1035_amb_DF_ION_WIN: CUP_nM1035_amb_DF_BASE {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1036_TOW_ION_WIN: CUP_nM1036_TOW_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1036_TOW_DF_ION_WIN: CUP_nM1036_TOW_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1037sc_ION_WIN: CUP_nM1037sc_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1037sc_DF_ION_WIN: CUP_nM1037sc_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1038_ION_WIN: CUP_nM1038_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1038_DF_ION_WIN: CUP_nM1038_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1038_4s_ION_WIN: CUP_nM1038_4s_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1038_4s_DF_ION_WIN: CUP_nM1038_4s_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1038_Ammo_ION_WIN: CUP_nM1038_Ammo_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1038_Ammo_DF_ION_WIN: CUP_nM1038_Ammo_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1038_Repair_ION_WIN: CUP_nM1038_Repair_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1038_Repair_DF_ION_WIN: CUP_nM1038_Repair_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1151_crowslp_m2_ION_WIN: CUP_ECVHMMWV_crowslp_m2_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1151_crowslp_m2_DF_ION_WIN: CUP_ECVHMMWV_crowslp_m2_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1151_ogpk_m2_ION_WIN: CUP_ECVHMMWV_ogpk_m2_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1151_ogpk_m2_DF_ION_WIN: CUP_ECVHMMWV_ogpk_m2_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1151_ogpk_m240_ION_WIN: CUP_ECVHMMWV_ogpk_m240_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1151_ogpk_m240_DF_ION_WIN: CUP_ECVHMMWV_ogpk_m240_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1151_ogpk_mk19_ION_WIN: CUP_ECVHMMWV_ogpk_mk19_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1151_ogpk_mk19_DF_ION_WIN: CUP_ECVHMMWV_ogpk_mk19_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1151_Unarmed_ION_WIN: CUP_ECVHMMWV_Unarmed_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_nM1151_Unarmed_DF_ION_WIN: CUP_ECVHMMWV_Unarmed_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_RG31_Mk19_W_ION: CUP_RG31_Mk19 {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_RG31E_M2_W_ION: CUP_RG31E_M2 {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_RG31_M2_W_ION: CUP_RG31_M2 {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_RG31_M2_W_GC_ION: CUP_RG31_M2_GC {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_Tigr_M_233114_ION_WIN: CUP_Tigr_233114_u_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_Tigr_M_233114_KORD_ION_WIN: CUP_Tigr_233114_KORD_Base {
    MACRO_HIDE_VEHICLE;
};

// Helicopters
class CUP_I_412_Military_Armed_PMC: CUP_412_Military_Armed_Base_F {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_412_Military_Armed_AT_PMC: CUP_412_Military_Armed_AT_Base_F {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_412_dynamicLoadout_PMC: CUP_412_dynamicLoadout_Base_F {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_412_Military_Radar_PMC: CUP_412_Military_Radar_Base_F {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_412_Mil_Transport_PMC: CUP_412_Mil_Transport_Base_F {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_412_Mil_Utility_PMC: CUP_412_Mil_Utility_Base_F {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_Merlin_HC3_PMC_Lux_3C: CUP_Merlin_HC3_Lux_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_Merlin_HC3_PMC_Lux_black: CUP_Merlin_HC3_Lux_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_Merlin_HC3_PMC_Transport_black: CUP_B_Merlin_HC3_GB {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_Ka60_GL_Blk_ION: CUP_Ka60_GL_BASE {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_MH6M_ION: CUP_B_MH6M_USA {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_MH6M_ION_OBS: CUP_B_MH6M_OBS_USA {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_Mi24_Mk3_ION: CUP_Mi35_TOH_Dynamic_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_Mi24_Mk4_ION: CUP_I_Mi24_Mk3_ION {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_Mi24_D_Dynamic_ION: CUP_Mi24_D_Dynamic_Base {
    MACRO_HIDE_VEHICLE;
};

// Planes
class CUP_I_Plane_ION: C_Plane_Civil_01_racing_F {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_CESSNA_T41_UNARMED_ION: cup_cessna_t41_base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_CESSNA_T41_ARMED_ION: cup_cessna_t41_armed_base {
    MACRO_HIDE_VEHICLE;
};
