// Anti Air
class CUP_I_LR_AA_RACS: CUP_LR_AA_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_M163_Vulcan_RACS: CUP_M163New_Base {
    MACRO_HIDE_VEHICLE;
};

// APCs
class CUP_I_M113A3_Repair_RACS: CUP_M113A3_Repair_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_AAV_Unarmed_RACS: CUP_B_AAV_Unarmed_USMC {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_AAV_RACS: CUP_AAV_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_LAV25_RACS: CUP_B_LAV25_USMC {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_LAV25M240_RACS: CUP_B_LAV25M240_USMC {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_LAV25_HQ_RACS: CUP_B_LAV25_HQ_USMC {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_M113A1_RACS: CUP_M113A1_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_M113A1_RACS_URB: CUP_M113A1_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_M113A1_Med_RACS: CUP_M113A1_Med_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_M113A3_Reammo_RACS: CUP_M113A3_Reammo_Base {
    MACRO_HIDE_VEHICLE;
};

// Artillery
class CUP_I_M270_HE_RACS: CUP_M270_HE_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_M270_DPICM_RACS: CUP_M270_DPICM_Base {
    MACRO_HIDE_VEHICLE;
};

// Boats
class CUP_I_LCU1600_RACS: CUP_LCU1600_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_LCVP_RACS: CUP_LCVP_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_LCVP_VIV_RACS: CUP_LCVP_VIV_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_Frigate_RACS: CUP_Frigate_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_RHIB_RACS: CUP_RHIB_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_RHIB2Turret_RACS: CUP_RHIB2Turret_Base {
    MACRO_HIDE_VEHICLE;
};

// Cars
class CUP_I_TowingTractor_RACS: CUP_TowingTractor_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_LR_Ambulance_RACS: CUP_LR_Ambulance_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_LR_MG_RACS: CUP_LR_MG_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_LR_Transport_RACS: CUP_LR_Transport_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_MTVR_RACS: CUP_MTVR_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_MTVR_Ammo_RACS: CUP_MTVR_Reammo_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_MTVR_Refuel_RACS: CUP_MTVR_Refuel_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_MTVR_Repair_RACS: CUP_MTVR_Repair_Base {
    MACRO_HIDE_VEHICLE;
};

// Helicopters
class CUP_I_UH60L_Unarmed_FFV_MEV_Racs: CUP_Uh60L_Unarmed_FFV_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_AH6J_RACS: CUP_B_AH6M_USA {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_CH47F_RACS: CUP_CH47F_base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_CH47F_VIV_RACS: CUP_CH47F_VIV_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_MH6J_RACS: CUP_B_MH6J_USA {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_SA330_Puma_HC1_RACS: CUP_B_SA330_Puma_HC1_BAF {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_SA330_Puma_HC2_RACS: CUP_B_SA330_Puma_HC2_BAF {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_UH1H_Armed_RACS: CUP_UH1H_armed_base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_UH1H_gunship_RACS: CUP_UH1H_gunship_base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_UH1H_Slick_RACS: CUP_UH1H_slick_base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_UH60L_FFV_RACS: CUP_Uh60L_FFV_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_UH60L_Unarmed_RACS: CUP_Uh60L_Unarmed_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_UH60L_Unarmed_FFV_Racs: CUP_Uh60L_Unarmed_FFV_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_UH1H_RACS: CUP_UH1H_base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_UH60L_RACS: CUP_Uh60L_Base {
    MACRO_HIDE_VEHICLE;
};

// Planes
class CUP_I_CESSNA_T41_ARMED_RACS: cup_cessna_t41_armed_base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_JAS39_RACS: Plane_Fighter_04_Base_F {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_C130J_RACS: CUP_C130J_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_C130J_Cargo_RACS: CUP_C130J_VIV_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_CESSNA_T41_UNARMED_RACS: cup_cessna_t41_base {
    MACRO_HIDE_VEHICLE;
};

// Tanks
class CUP_I_T72_RACS: CUP_T72_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_M60A3_RACS: CUP_M60A3_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_I_M60A3_TTS_RACS: CUP_M60A3_TTS_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1A2SEP_RACS: CUP_M1Abrams_M1A2SEP_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1A2SEP_TUSK_RACS: CUP_M1Abrams_M1A2SEP_TUSK_Base {
    MACRO_HIDE_VEHICLE;
};
