// APCs
class CUP_B_M1126_ICV_M2_Desert: CUP_M1126_ICV_BASE {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1126_ICV_MK19_Desert: CUP_M1126_ICV_BASE {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1128_MGS_Desert: CUP_StrykerBase {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1130_CV_M2_Desert: CUP_B_M1126_ICV_M2_Desert {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1133_MEV_Desert: CUP_M1126_ICV_BASE {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1135_ATGMV_Desert: CUP_StrykerBase {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M113A1_desert_USA: CUP_M113A1_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M113A1_HQ_desert_USA: CUP_M113A1_HQ_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M113A1_Med_desert_USA: CUP_M113A1_Med_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M113A3_desert_USA: CUP_M113A3_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M113A3_Reammo_desert_USA: CUP_M113A3_Reammo_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M113A3_Repair_desert_USA: CUP_M113A3_Repair_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M113A3_Med_desert_USA: CUP_M113A3_Med_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M113A3_HQ_desert_USA: CUP_M113A3_HQ_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M2Bradley_USA_D: CUP_M2Bradley_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M2A3Bradley_USA_D: CUP_B_M2Bradley_USA_D {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M7Bradley_USA_D: CUP_B_M2Bradley_USA_D {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M113A3_Med_olive_USA: CUP_M113A3_Med_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M113A3_HQ_olive_USA: CUP_M113A3_HQ_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M113A3_Repair_olive_USA: CUP_M113A3_Repair_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M113A3_Reammo_olive_USA: CUP_M113A3_Reammo_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M113A3_olive_USA: CUP_M113A3_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M113A1_Med_olive_USA: CUP_M113A1_Med_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M113A1_HQ_olive_USA: CUP_M113A1_HQ_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M113A1_olive_USA: CUP_M113A1_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1126_ICV_M2_Woodland: CUP_B_M1126_ICV_M2_Desert {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1126_ICV_MK19_Woodland: CUP_B_M1126_ICV_MK19_Desert {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1128_MGS_Woodland: CUP_B_M1128_MGS_Desert {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1130_CV_M2_Woodland: CUP_B_M1130_CV_M2_Desert {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1133_MEV_Woodland: CUP_B_M1133_MEV_Desert {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1135_ATGMV_Woodland: CUP_B_M1135_ATGMV_Desert {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M113A1_USA: CUP_M113A1_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M113A1_HQ_USA: CUP_M113A1_HQ_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M113A1_Med_USA: CUP_M113A1_Med_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M113A3_USA: CUP_M113A3_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M113A3_Reammo_USA: CUP_M113A3_Reammo_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M113A3_Repair_USA: CUP_M113A3_Repair_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M113A3_HQ_USA: CUP_M113A3_HQ_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M113A3_Med_USA: CUP_M113A3_Med_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M2Bradley_USA_W: CUP_B_M2Bradley_USA_D {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M2A3Bradley_USA_W: CUP_B_M2A3Bradley_USA_D {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M7Bradley_USA_W: CUP_B_M2Bradley_USA_D {
    MACRO_HIDE_VEHICLE;
};

// Anti Air
class CUP_B_nM1097_AVENGER_USA_DES: CUP_nM1097_Avenger_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1097_AVENGER_USA_WDL: CUP_nM1097_Avenger_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M163_Vulcan_USA: CUP_M163New_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M6LineBacker_USA_D: CUP_B_M2Bradley_USA_D {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M6LineBacker_USA_W: CUP_B_M6LineBacker_USA_D {
    MACRO_HIDE_VEHICLE;
};

// Artillery
class CUP_B_M1129_MC_MK19_Desert: CUP_B_M1126_ICV_MK19_Desert {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1129_MC_MK19_Woodland: CUP_B_M1129_MC_MK19_Desert {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M270_DPICM_USA: CUP_M270_DPICM_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M270_HE_USA: CUP_M270_HE_Base {
    MACRO_HIDE_VEHICLE;
};

// Bikes
class CUP_B_M1030_USA: CUP_M1030_Base {
    MACRO_HIDE_VEHICLE;
};

// Cars
class CUP_B_HMMWV_Crows_M2_USA: CUP_HMMWV_Crows_M2_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_HMMWV_Crows_MK19_USA: CUP_HMMWV_crows_MK19_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1025_M2_USA_DES: CUP_nM1025_M2_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_HMMWV_M2_GPK_USA: CUP_HMMWV_M2_GPK_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1025_M2_DF_USA_DES: CUP_nM1025_M2_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1025_M240_USA_DES: CUP_nM1025_M240_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1025_M240_DF_USA_DES: CUP_nM1025_M240_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1025_Mk19_USA_DES: CUP_nM1025_Mk19_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1025_Mk19_DF_USA_DES: CUP_nM1025_Mk19_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1025_Unarmed_USA_DES: CUP_nM1025_Unarmed_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1025_Unarmed_DF_USA_DES: CUP_nM1025_Unarmed_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1025_SOV_M2_USA_DES: CUP_nM1025_SOV_M2_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1025_SOV_Mk19_USA_DES: CUP_nM1025_SOV_Mk19_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1036_TOW_USA_DES: CUP_nM1036_TOW_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1036_TOW_DF_USA_DES: CUP_nM1036_TOW_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1037sc_USA_DES: CUP_nM1037sc_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1037sc_DF_USA_DES: CUP_nM1037sc_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1038_USA_DES: CUP_nM1038_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1038_DF_USA_DES: CUP_nM1038_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1038_4s_USA_DES: CUP_nM1038_4s_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1038_4s_DF_USA_DES: CUP_nM1038_4s_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1038_Ammo_USA_DES: CUP_nM1038_Ammo_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1038_Ammo_DF_USA_DES: CUP_nM1038_Ammo_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1038_Repair_USA_DES: CUP_nM1038_Repair_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1038_Repair_DF_USA_DES: CUP_nM1038_Repair_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1151_ogpk_m2_USA_DES: CUP_ECVHMMWV_ogpk_m2_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1151_ogpk_m2_DF_USA_DES: CUP_ECVHMMWV_ogpk_m2_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1151_ogpk_m240_USA_DES: CUP_ECVHMMWV_ogpk_m240_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1151_ogpk_m240_DF_USA_DES: CUP_ECVHMMWV_ogpk_m240_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1151_ogpk_mk19_USA_DES: CUP_ECVHMMWV_ogpk_mk19_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1151_ogpk_mk19_DF_USA_DES: CUP_ECVHMMWV_ogpk_mk19_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1151_Unarmed_USA_DES: CUP_ECVHMMWV_Unarmed_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1151_Unarmed_DF_USA_DES: CUP_ECVHMMWV_Unarmed_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1151_M2_USA: CUP_M1151_M2_BASE {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1151_Deploy_USA: CUP_M1151_Deploy_BASE {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1151_Mk19_USA: CUP_M1151_Mk19_BASE {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1151_USA: CUP_M1151_Unarmed_BASE {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1152_USA: CUP_M1152_BASE {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1165_GMV_USA: CUP_M1165_GMV_BASE {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1167_USA: CUP_M1167_BASE {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM997_USA_DES: CUP_nM997_amb_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM997_DF_USA_DES: CUP_nM997_amb_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_MTVR_USA: CUP_MTVR_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_MTVR_Ammo_USA: CUP_MTVR_Reammo_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_MTVR_Refuel_USA: CUP_MTVR_Refuel_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_MTVR_Repair_USA: CUP_MTVR_Repair_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_RG31_Mk19_USA: CUP_RG31_Mk19 {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_RG31E_M2_USA: CUP_RG31E_M2 {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_RG31_M2_USA: CUP_RG31_M2 {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_RG31_M2_GC_USA: CUP_RG31_M2_GC {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_TowingTractor_USA: CUP_TowingTractor_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1025_M2_USA_WDL: CUP_nM1025_M2_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1025_M2_DF_USA_WDL: CUP_nM1025_M2_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1025_M240_USA_WDL: CUP_nM1025_M240_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1025_M240_DF_USA_WDL: CUP_nM1025_M240_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1025_Mk19_USA_WDL: CUP_nM1025_Mk19_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1025_Mk19_DF_USA_WDL: CUP_nM1025_Mk19_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1025_Unarmed_USA_WDL: CUP_nM1025_Unarmed_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1025_Unarmed_DF_USA_WDL: CUP_nM1025_Unarmed_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1025_SOV_M2_USA_WDL: CUP_nM1025_SOV_M2_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1025_SOV_Mk19_USA_WDL: CUP_nM1025_SOV_Mk19_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1036_TOW_USA_WDL: CUP_nM1036_TOW_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1036_TOW_DF_USA_WDL: CUP_nM1036_TOW_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1037sc_USA_WDL: CUP_nM1037sc_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1037sc_DF_USA_WDL: CUP_nM1037sc_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1038_USA_WDL: CUP_nM1038_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1038_DF_USA_WDL: CUP_nM1038_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1038_4s_USA_WDL: CUP_nM1038_4s_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1038_Ammo_USA_WDL: CUP_nM1038_Ammo_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1038_4s_DF_USA_WDL: CUP_nM1038_4s_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1038_Ammo_DF_USA_WDL: CUP_nM1038_Ammo_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1038_Repair_USA_WDL: CUP_nM1038_Repair_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1038_Repair_DF_USA_WDL: CUP_nM1038_Repair_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1151_ogpk_m2_USA_WDL: CUP_ECVHMMWV_ogpk_m2_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1151_ogpk_m2_DF_USA_WDL: CUP_ECVHMMWV_ogpk_m2_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1151_ogpk_m240_USA_WDL: CUP_ECVHMMWV_ogpk_m240_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1151_ogpk_m240_DF_USA_WDL: CUP_ECVHMMWV_ogpk_m240_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1151_ogpk_mk19_USA_WDL: CUP_ECVHMMWV_ogpk_mk19_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1151_ogpk_mk19_DF_USA_WDL: CUP_ECVHMMWV_ogpk_mk19_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1151_Unarmed_USA_WDL: CUP_ECVHMMWV_Unarmed_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1151_Unarmed_DF_USA_WDL: CUP_ECVHMMWV_Unarmed_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1151_M2_WDL_USA: CUP_M1151_M2_BASE {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1151_Deploy_WDL_USA: CUP_M1151_Deploy_BASE {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1151_Mk19_WDL_USA: CUP_M1151_Mk19_BASE {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1151_WDL_USA: CUP_M1151_Unarmed_BASE {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1152_WDL_USA: CUP_M1152_BASE {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1165_GMV_WDL_USA: CUP_M1165_GMV_BASE {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1167_WDL_USA: CUP_M1167_BASE {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM997_USA_WDL: CUP_nM997_amb_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM997_DF_USA_WDL: CUP_nM997_amb_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_RG31_Mk19_OD_USA: CUP_RG31_Mk19 {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_RG31E_M2_OD_USA: CUP_RG31E_M2 {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_RG31_M2_OD_USA: CUP_RG31_M2 {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_RG31_M2_OD_GC_USA: CUP_RG31_M2_GC {
    MACRO_HIDE_VEHICLE;
};

// Drones
class CUP_B_AH6X_USA: CUP_AH6_BASE {
    MACRO_HIDE_VEHICLE;
};

// Helicopters
class CUP_B_AH64_DL_USA: CUP_AH64_dynamic_base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_AH64D_DL_USA: CUP_AH64D_dynamic_base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_AH6M_USA: CUP_AH6_DYNLOAD {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_AH6J_USA: CUP_B_AH6M_USA {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_CH47F_USA: CUP_CH47F_base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_MH47E_USA: CUP_MH47E_base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_MH60L_DAP_2x_US: CUP_MH60L_Dap_2x_Dynamic_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_MH60L_DAP_4x_US: CUP_MH60L_Dap_4x_Dynamic_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_MH6M_USA: CUP_MH6_TRANSPORT {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_UH60M_FFV_US: CUP_Uh60_FFV_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_UH60M_Unarmed_US: CUP_UH60_Unarmed_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_UH60M_Unarmed_FFV_US: CUP_Uh60_Unarmed_FFV_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_UH60M_Unarmed_FFV_MEV_US: CUP_Uh60_Unarmed_FFV_Base {
    MACRO_HIDE_VEHICLE;
};

// Planes
class CUP_B_A10_DYN_USA: CUP_B_A10_CAS_USA {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_AC47_Spooky_USA: CUP_AC47_Spooky_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_C47_USA: CUP_C47_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_CESSNA_T41_UNARMED_USA: cup_cessna_t41_base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_CESSNA_T41_ARMED_USA: cup_cessna_t41_armed_base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_CESSNA_T41_UNARMED_AIRFORCE_USA: cup_cessna_t41_base {
    MACRO_HIDE_VEHICLE;
};

// Tanks
class CUP_B_M1A1SA_Desert_US_Army: CUP_M1Abramcs_M1A1SA_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1A1SA_Desert_TUSK_US_Army: CUP_M1Abrams_M1A1SA_TUSK_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1A2SEP_Desert_US_Army: CUP_M1Abrams_M1A2SEP_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1A2SEP_TUSK_II_Desert_US_Army: CUP_M1Abrams_A2_TUSK_II_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1A2SEP_TUSK_Desert_US_Army: CUP_M1Abrams_M1A2SEP_TUSK_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1A2C_Desert_US_Army: CUP_M1A2Abrams_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1A2C_TUSK_II_Desert_US_Army: CUP_M1A2Abrams_TUSK_II_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1A2C_TUSK_Desert_US_Army: CUP_M1A2Abrams_TUSK_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1A1SA_OD_US_Army: CUP_M1Abramcs_M1A1SA_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1A1SA_TUSK_OD_US_Army: CUP_M1Abrams_M1A1SA_TUSK_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1A2SEP_TUSK_II_OD_US_Army: CUP_M1Abrams_A2_TUSK_II_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1A2SEP_OD_US_Army: CUP_M1Abrams_M1A2SEP_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1A2SEP_TUSK_OD_US_Army: CUP_M1Abrams_M1A2SEP_TUSK_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1A2C_TUSK_II_OD_US_Army: CUP_M1A2Abrams_TUSK_II_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1A2C_TUSK_OD_US_Army: CUP_M1A2Abrams_TUSK_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1A1SA_Woodland_US_Army: CUP_M1Abramcs_M1A1SA_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1A1SA_TUSK_Woodland_US_Army: CUP_M1Abrams_M1A1SA_TUSK_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1A2SEP_Woodland_US_Army: CUP_M1Abrams_M1A2SEP_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1A2SEP_TUSK_II_Woodland_US_Army: CUP_M1Abrams_A2_TUSK_II_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1A2SEP_TUSK_Woodland_US_Army: CUP_M1Abrams_M1A2SEP_TUSK_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1A2C_Woodland_US_Army: CUP_M1A2Abrams_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1A2C_TUSK_II_Woodland_US_Army: CUP_M1A2Abrams_TUSK_II_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1A2C_TUSK_Woodland_US_Army: CUP_M1A2Abrams_TUSK_Base {
    MACRO_HIDE_VEHICLE;
};
