class CfgWeapons {
    class acc_flashlight;
    class cup_acc_flashlight;
    class CUP_acc_Flashlight_desert;
    class CUP_acc_Flashlight_wdl;
    class cup_acc_anpeq_15_top_flashlight_black_l;
    class CUP_acc_anpeq_15_top_Flashlight_Black_f;
    class CUP_acc_anpeq_15_top_Flashlight_Black_v;
    class cup_acc_anpeq_15_top_flashlight_tan_l;
    class cup_acc_anpeq_15_top_flashlight_tan_f;
    class cup_acc_anpeq_15_top_flashlight_tan_v;
    class cup_acc_anpeq_15_top_flashlight_od_l;
    class cup_acc_anpeq_15_top_flashlight_od_f;
    class cup_acc_anpeq_15_top_flashlight_od_v;
    class cup_acc_anpeq_15_flashlight_black_l;
    class cup_acc_anpeq_15_flashlight_black_f;
    class CUP_acc_anpeq_15_flashlight_black_v;
    class cup_acc_anpeq_15_flashlight_tan_l;
    class cup_acc_anpeq_15_flashlight_tan_f;
    class cup_acc_anpeq_15_flashlight_tan_v;
    class cup_acc_anpeq_15_flashlight_od_l;
    class cup_acc_anpeq_15_flashlight_od_f;
    class cup_acc_anpeq_15_flashlight_od_v;
    class InventoryFlashLightItem_Base_F;

    FLASHLIGHT(UTG_flashlight, acc_flashlight, UTG_Flashlight_Display, Description);
    FLASHLIGHT(Surefire_Flashlight_Black, cup_acc_flashlight, Surefire_Flashlight_Black_Display, Description);
    FLASHLIGHT(Surefire_Flashlight_OD, CUP_acc_Flashlight_wdl, Surefire_Flashlight_OD_Display, Description);
    FLASHLIGHT(Surefire_Flashlight_Tan, CUP_acc_Flashlight_desert, Surefire_Flashlight_Tan_Display, Description);
    ANPEQLaser(ANPEQ_15_Top_Laser_Black, cup_acc_anpeq_15_top_flashlight_black_l, ANPEQ_15_Top_Laser_Light_Black_Display, ANPEQ_Description, ANPEQ_15_Top_Light_Black);
    ANPEQLight(ANPEQ_15_Top_Light_Black, cup_acc_anpeq_15_top_flashlight_black_f, ANPEQ_15_Top_Laser_Light_Black_Display, ANPEQ_Description, ANPEQ_15_Top_Laser_Black);
    ANPEQVIS(ANPEQ_15_Top_Vis_Laser_Black, cup_acc_anpeq_15_top_flashlight_black_v, ANPEQ_15_Top_Laser_Light_Black_Display, ANPEQ_Description, ANPEQ_15_Top_Light_Black, ANPEQ_15_Top_Laser_Black);
    ANPEQLaser(ANPEQ_15_Top_Light_Tan, cup_acc_anpeq_15_top_flashlight_tan_l, ANPEQ_15_Top_Laser_Light_Tan_Display, ANPEQ_Description, ANPEQ_15_Top_Laser_Tan);
    ANPEQLight(ANPEQ_15_Top_Laser_Tan, cup_acc_anpeq_15_top_flashlight_tan_f, ANPEQ_15_Top_Laser_Light_Tan_Display, ANPEQ_Description, ANPEQ_15_Top_Light_Tan);
    ANPEQVIS(ANPEQ_15_Top_Vis_Laser_Tan, cup_acc_anpeq_15_top_flashlight_tan_v, ANPEQ_15_Top_Laser_Light_Tan_Display, ANPEQ_Description, ANPEQ_15_Top_Light_Tan, ANPEQ_15_Top_Laser_Tan);
    ANPEQLaser(ANPEQ_15_Top_Light_OD, cup_acc_anpeq_15_top_flashlight_od_l, ANPEQ_15_Top_Laser_Light_OD_Display, ANPEQ_Description, ANPEQ_15_Top_Laser_OD);
    ANPEQLight(ANPEQ_15_Top_Laser_OD, cup_acc_anpeq_15_top_flashlight_od_f, ANPEQ_15_Top_Laser_Light_OD_Display, ANPEQ_Description, ANPEQ_15_Top_Light_OD);
    ANPEQVIS(ANPEQ_15_Top_Vis_Laser_OD, cup_acc_anpeq_15_top_flashlight_od_v, ANPEQ_15_Top_Laser_Light_OD_Display, ANPEQ_Description, ANPEQ_15_Top_Light_OD, ANPEQ_15_Top_Laser_OD);
    ANPEQLaser(ANPEQ_15_Light_Black, cup_acc_anpeq_15_flashlight_black_l, ANPEQ_15_Laser_Light_Black_Display, ANPEQ_Description, ANPEQ_15_Laser_Black);
    ANPEQLight(ANPEQ_15_Laser_Black, cup_acc_anpeq_15_flashlight_black_f, ANPEQ_15_Laser_Light_Black_Display, ANPEQ_Description, ANPEQ_15_Light_Black);
    ANPEQVIS(ANPEQ_15_Vis_Laser_Black, cup_acc_anpeq_15_flashlight_black_v, ANPEQ_15_Laser_Light_Black_Display, ANPEQ_Description, ANPEQ_15_Light_Black, ANPEQ_15_Laser_Black);
    ANPEQLaser(ANPEQ_15_Light_Tan, cup_acc_anpeq_15_flashlight_tan_l, ANPEQ_15_Laser_Light_Tan_Display, ANPEQ_Description, ANPEQ_15_Laser_Tan);
    ANPEQLight(ANPEQ_15_Laser_Tan, cup_acc_anpeq_15_flashlight_tan_f, ANPEQ_15_Laser_Light_Tan_Display, ANPEQ_Description, ANPEQ_15_Light_Tan);
    ANPEQVIS(ANPEQ_15_Vis_Laser_Tan, cup_acc_anpeq_15_flashlight_tan_v, ANPEQ_15_Laser_Light_Tan_Display, ANPEQ_Description, ANPEQ_15_Light_Tan, ANPEQ_15_Laser_Tan);
    ANPEQLaser(ANPEQ_15_Light_OD, cup_acc_anpeq_15_flashlight_od_l, ANPEQ_15_Laser_Light_OD_Display, ANPEQ_Description, ANPEQ_15_Laser_OD);
    ANPEQLight(ANPEQ_15_Laser_OD, cup_acc_anpeq_15_flashlight_od_f, ANPEQ_15_Laser_Light_OD_Display, ANPEQ_Description, ANPEQ_15_Light_OD);
    ANPEQVIS(ANPEQ_15_Vis_Laser_OD, cup_acc_anpeq_15_flashlight_od_v, ANPEQ_15_Laser_Light_OD_Display, ANPEQ_Description, ANPEQ_15_Light_OD, ANPEQ_15_Laser_OD);
};
