class CfgWeapons {
    class acc_flashlight;
    class cup_acc_flashlight;
    class CUP_acc_Flashlight_desert;
    class CUP_acc_Flashlight_wdl;
    class cup_acc_anpeq_15_top_flashlight_black_l;
    class CUP_acc_anpeq_15_top_Flashlight_Black_f;
    class CUP_acc_anpeq_15_top_Flashlight_Black_v;
    class cup_acc_anpeq_15_top_flashlight_tan_l;
    class cup_acc_anpeq_15_top_flashlight_tan_f;
    class cup_acc_anpeq_15_top_flashlight_tan_v;
    class cup_acc_anpeq_15_top_flashlight_od_l;
    class cup_acc_anpeq_15_top_flashlight_od_f;
    class cup_acc_anpeq_15_top_flashlight_od_v;
    class cup_acc_anpeq_15_flashlight_black_l;
    class cup_acc_anpeq_15_flashlight_black_f;
    class CUP_acc_anpeq_15_flashlight_black_v;
    class cup_acc_anpeq_15_flashlight_tan_l;
    class cup_acc_anpeq_15_flashlight_tan_f;
    class cup_acc_anpeq_15_flashlight_tan_v;
    class cup_acc_anpeq_15_flashlight_od_l;
    class cup_acc_anpeq_15_flashlight_od_f;
    class cup_acc_anpeq_15_flashlight_od_v;
    class BWA3_acc_LLM01_irlaser;
    class BWA3_acc_LLM01_flash;
    class BWA3_acc_LLM01_laser;
    class BWA3_acc_LLM01_irlaser_tan;
    class BWA3_acc_LLM01_flash_tan;
    class BWA3_acc_LLM01_laser_tan;
    class BWA3_acc_VarioRay_irlaser;
    class BWA3_acc_VarioRay_flash;
    class BWA3_acc_VarioRay_laser;
    class BWA3_acc_VarioRay_irlaser_black;
    class BWA3_acc_VarioRay_flash_black;
    class BWA3_acc_VarioRay_laser_black;
    class InventoryFlashLightItem_Base_F;

    FLASHLIGHT(UTG_flashlight, acc_flashlight, UTG_Flashlight_Display, Description);
    FLASHLIGHT(Surefire_Flashlight_Black, cup_acc_flashlight, Surefire_Flashlight_Black_Display, Description);
    FLASHLIGHT(Surefire_Flashlight_OD, CUP_acc_Flashlight_wdl, Surefire_Flashlight_OD_Display, Description);
    FLASHLIGHT(Surefire_Flashlight_Tan, CUP_acc_Flashlight_desert, Surefire_Flashlight_Tan_Display, Description);
    SWITCHIR(ANPEQ_15_Top_Laser_Black, cup_acc_anpeq_15_top_flashlight_black_l, ANPEQ_15_Top_Laser_Light_Black_Display, Multi_Description, ANPEQ_15_Top_Light_Black);
    SWITCHLIGHT(ANPEQ_15_Top_Light_Black, cup_acc_anpeq_15_top_flashlight_black_f, ANPEQ_15_Top_Laser_Light_Black_Display, Multi_Description, ANPEQ_15_Top_Vis_Laser_Black);
    SWITCHLASER(ANPEQ_15_Top_Vis_Laser_Black, cup_acc_anpeq_15_top_flashlight_black_v, ANPEQ_15_Top_Laser_Light_Black_Display, Multi_Description, ANPEQ_15_Top_Laser_Black);
    SWITCHIR(ANPEQ_15_Top_Light_Tan, cup_acc_anpeq_15_top_flashlight_tan_l, ANPEQ_15_Top_Laser_Light_Tan_Display, Multi_Description, ANPEQ_15_Top_Laser_Tan);
    SWITCHLIGHT(ANPEQ_15_Top_Laser_Tan, cup_acc_anpeq_15_top_flashlight_tan_f, ANPEQ_15_Top_Laser_Light_Tan_Display, Multi_Description, ANPEQ_15_Top_Vis_Laser_Tan);
    SWITCHLASER(ANPEQ_15_Top_Vis_Laser_Tan, cup_acc_anpeq_15_top_flashlight_tan_v, ANPEQ_15_Top_Laser_Light_Tan_Display, Multi_Description, ANPEQ_15_Top_Light_Tan);
    SWITCHIR(ANPEQ_15_Top_Light_OD, cup_acc_anpeq_15_top_flashlight_od_l, ANPEQ_15_Top_Laser_Light_OD_Display, Multi_Description, ANPEQ_15_Top_Laser_OD);
    SWITCHLIGHT(ANPEQ_15_Top_Laser_OD, cup_acc_anpeq_15_top_flashlight_od_f, ANPEQ_15_Top_Laser_Light_OD_Display, Multi_Description, ANPEQ_15_Top_Vis_Laser_OD);
    SWITCHLASER(ANPEQ_15_Top_Vis_Laser_OD, cup_acc_anpeq_15_top_flashlight_od_v, ANPEQ_15_Top_Laser_Light_OD_Display, Multi_Description, ANPEQ_15_Top_Light_OD);
    SWITCHIR(ANPEQ_15_Light_Black, cup_acc_anpeq_15_flashlight_black_l, ANPEQ_15_Laser_Light_Black_Display, Multi_Description, ANPEQ_15_Laser_Black);
    SWITCHLIGHT(ANPEQ_15_Laser_Black, cup_acc_anpeq_15_flashlight_black_f, ANPEQ_15_Laser_Light_Black_Display, Multi_Description, ANPEQ_15_Vis_Laser_Black);
    SWITCHLASER(ANPEQ_15_Vis_Laser_Black, cup_acc_anpeq_15_flashlight_black_v, ANPEQ_15_Laser_Light_Black_Display, Multi_Description, ANPEQ_15_Light_Black);
    SWITCHIR(ANPEQ_15_Light_Tan, cup_acc_anpeq_15_flashlight_tan_l, ANPEQ_15_Laser_Light_Tan_Display, Multi_Description, ANPEQ_15_Laser_Tan);
    SWITCHLIGHT(ANPEQ_15_Laser_Tan, cup_acc_anpeq_15_flashlight_tan_f, ANPEQ_15_Laser_Light_Tan_Display, Multi_Description, ANPEQ_15_Vis_Laser_Tan);
    SWITCHLASER(ANPEQ_15_Vis_Laser_Tan, cup_acc_anpeq_15_flashlight_tan_v, ANPEQ_15_Laser_Light_Tan_Display, Multi_Description, ANPEQ_15_Light_Tan);
    SWITCHIR(ANPEQ_15_Light_OD, cup_acc_anpeq_15_flashlight_od_l, ANPEQ_15_Laser_Light_OD_Display, Multi_Description, ANPEQ_15_Laser_OD);
    SWITCHLIGHT(ANPEQ_15_Laser_OD, cup_acc_anpeq_15_flashlight_od_f, ANPEQ_15_Laser_Light_OD_Display, Multi_Description, ANPEQ_15_Vis_Laser_OD);
    SWITCHLASER(ANPEQ_15_Vis_Laser_OD, cup_acc_anpeq_15_flashlight_od_v, ANPEQ_15_Laser_Light_OD_Display, Multi_Description, ANPEQ_15_Light_OD);
    SWITCHIR(LLM01_IR_Laser_Black, BWA3_acc_LLM01_irlaser, LLM01_IR_Laser_Black_Display, Multi_Description, LLM01_IR_Light_Black);
    SWITCHLIGHT(LLM01_IR_Light_Black, BWA3_acc_LLM01_flash, LLM01_IR_Laser_Black_Display, Multi_Description, LLM01_Vis_Laser_Black);
    SWITCHLASER(LLM01_Vis_Laser_Black, BWA3_acc_LLM01_laser, LLM01_IR_Laser_Black_Display, Multi_Description, LLM01_IR_Laser_Black);
    SWITCHIR(LLM01_IR_Laser_Tan, BWA3_acc_LLM01_irlaser_tan, LLM01_IR_Laser_Tan_Display, Multi_Description, LLM01_IR_Light_Tan);
    SWITCHLIGHT(LLM01_IR_Light_Tan, BWA3_acc_LLM01_flash_tan, LLM01_IR_Laser_Tan_Display, Multi_Description, LLM01_Vis_Laser_Tan);
    SWITCHLASER(LLM01_Vis_Laser_Tan, BWA3_acc_LLM01_laser_tan, LLM01_IR_Laser_Tan_Display, Multi_Description, LLM01_IR_Laser_Tan);
    SWITCHIR(VarioRay_IR_Laser_Tan, BWA3_acc_VarioRay_irlaser, VarioRay_IR_Laser_Tan_Display, Multi_Description, VarioRay_IR_Light_Tan);
    SWITCHLIGHT(VarioRay_IR_Light_Tan, BWA3_acc_VarioRay_flash, VarioRay_IR_Laser_Tan_Display, Multi_Description, VarioRay_Vis_Laser_Tan);
    SWITCHLASER(VarioRay_Vis_Laser_Tan, BWA3_acc_VarioRay_laser, VarioRay_IR_Laser_Tan_Display, Multi_Description, VarioRay_IR_Laser_Tan);
    SWITCHIR(VarioRay_IR_Laser_Black, BWA3_acc_VarioRay_irlaser_black, VarioRay_IR_Laser_Black_Display, Multi_Description, VarioRay_IR_Light_Black);
    SWITCHLIGHT(VarioRay_IR_Light_Black, BWA3_acc_VarioRay_flash_black, VarioRay_IR_Laser_Black_Display, Multi_Description, VarioRay_Vis_Laser_Black);
    SWITCHLASER(VarioRay_Vis_Laser_Black, BWA3_acc_VarioRay_laser_black, VarioRay_IR_Laser_Black_Display, Multi_Description, VarioRay_IR_Laser_Black);
};
