[
    QCLASS(IFAK),
    [
        "ACE_bodyBag",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_splint",
        "ACE_splint",
        "ACE_tourniquet",
        "ACE_tourniquet",
        "ACE_tourniquet",
        "ACE_tourniquet",
        "tac_medical_painkillers",
        "tac_medical_painkillers"
    ]
] call ace_common_fnc_registerItemReplacement;
