// Anti Air
class CUP_B_nM1097_AVENGER_USMC_WDL: CUP_nM1097_Avenger_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1097_AVENGER_USMC_DES: CUP_nM1097_Avenger_Base {
    MACRO_HIDE_VEHICLE;
};

// APCs
class CUP_B_AAV_Unarmed_USMC: CUP_AAV_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_AAV_USMC: CUP_AAV_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_AAV_USMC_TTS: CUP_AAV_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_LAV25_USMC: CUP_LAV25_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_LAV25_desert_USMC: CUP_B_LAV25_USMC {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_LAV25M240_USMC: CUP_B_LAV25_USMC {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_LAV25M240_desert_USMC: CUP_B_LAV25M240_USMC {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_LAV25M240_green: CUP_B_LAV25M240_USMC {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_LAV25_green: CUP_B_LAV25_USMC {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_LAV25_HQ_USMC: CUP_B_LAV25_USMC {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_LAV25_HQ_desert_USMC: CUP_B_LAV25_HQ_USMC {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_LAV25_HQ_green: CUP_B_LAV25_HQ_USMC {
    MACRO_HIDE_VEHICLE;
};

// Artillery
class CUP_B_M270_DPICM_USMC: CUP_M270_DPICM_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M270_HE_USMC: CUP_M270_HE_Base {
    MACRO_HIDE_VEHICLE;
};

// Bikes
class CUP_B_M1030_USMC: CUP_M1030_Base {
    MACRO_HIDE_VEHICLE;
};

// Boats
class CUP_B_LCU1600_USMC: CUP_LCU1600_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_RHIB_USMC: CUP_RHIB_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_RHIB2Turret_USMC: CUP_RHIB2Turret_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_Seafox_USMC: CUP_Seafox_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_Zodiac_USMC: Rubber_duck_base_F {
    MACRO_HIDE_VEHICLE;
};

// Cars
class CUP_B_RG31E_M2_USMC: CUP_RG31E_M2 {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1038_Ammo_USMC_DES: CUP_nM1038_Ammo_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1151_Unarmed_USMC_DES: CUP_ECVHMMWV_Unarmed_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1151_Deploy_DSRT_USMC: CUP_M1151_Deploy_BASE {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM997_USMC_DES: CUP_nM997_amb_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1025_M2_USMC_WDL: CUP_nM1025_M2_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1025_M2_DF_USMC_WDL: CUP_nM1025_M2_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1025_M240_DF_USMC_WDL: CUP_nM1025_M240_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1025_M240_USMC_WDL: CUP_nM1025_M240_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1025_Mk19_USMC_WDL: CUP_nM1025_Mk19_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1025_Mk19_DF_USMC_WDL: CUP_nM1025_Mk19_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1025_Unarmed_USMC_WDL: CUP_nM1025_Unarmed_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1025_Unarmed_DF_USMC_WDL: CUP_nM1025_Unarmed_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1025_SOV_M2_USMC_WDL: CUP_nM1025_SOV_M2_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1025_SOV_Mk19_USMC_WDL: CUP_nM1025_SOV_Mk19_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1036_TOW_USMC_WDL: CUP_nM1036_TOW_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1036_TOW_DF_USMC_WDL: CUP_nM1036_TOW_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1037sc_USMC_WDL: CUP_nM1037sc_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1037sc_DF_USMC_WDL: CUP_nM1037sc_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1038_USMC_WDL: CUP_nM1038_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1038_DF_USMC_WDL: CUP_nM1038_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1038_4s_USMC_WDL: CUP_nM1038_4s_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1038_4s_DF_USMC_WDL: CUP_nM1038_4s_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1038_Ammo_USMC_WDL: CUP_nM1038_Ammo_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1038_Ammo_DF_USMC_WDL: CUP_nM1038_Ammo_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1038_Repair_USMC_WDL: CUP_nM1038_Repair_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1038_Repair_DF_USMC_WDL: CUP_nM1038_Repair_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1151_mctags_m2_USMC_WDL: CUP_ECVHMMWV_ogpk_m2_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1151_mctags_m2_DF_USMC_WDL: CUP_ECVHMMWV_ogpk_m2_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1151_mctags_m240_USMC_WDL: CUP_ECVHMMWV_ogpk_m240_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1151_mctags_m240_DF_USMC_WDL: CUP_ECVHMMWV_ogpk_m240_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1151_mctags_mk19_USMC_WDL: CUP_ECVHMMWV_ogpk_mk19_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1151_mctags_mk19_DF_USMC_WDL: CUP_ECVHMMWV_ogpk_mk19_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1151_Unarmed_USMC_WDL: CUP_ECVHMMWV_Unarmed_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1151_Unarmed_DF_USMC_WDL: CUP_ECVHMMWV_Unarmed_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1151_M2_USMC: CUP_M1151_M2_BASE {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1151_Deploy_USMC: CUP_M1151_Deploy_BASE {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1151_Mk19_USMC: CUP_M1151_Mk19_BASE {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1151_USMC: CUP_M1151_Unarmed_BASE {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1152_USMC: CUP_M1152_BASE {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1165_GMV_USMC: CUP_M1165_GMV_BASE {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1167_USMC: CUP_M1167_BASE {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM997_USMC_WDL: CUP_nM997_amb_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM997_DF_USMC_WDL: CUP_nM997_amb_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_MTVR_USMC: CUP_MTVR_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_MTVR_Ammo_USMC: CUP_MTVR_Reammo_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_MTVR_Refuel_USMC: CUP_MTVR_Refuel_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_MTVR_Repair_USMC: CUP_MTVR_Repair_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_RG31_Mk19_OD_USMC: CUP_RG31_Mk19 {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_RG31E_M2_OD_USMC: CUP_RG31E_M2 {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_RG31_M2_OD_USMC: CUP_RG31_M2 {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_RG31_M2_OD_GC_USMC: CUP_RG31_M2_GC {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_TowingTractor_USMC: CUP_TowingTractor_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1025_M2_USMC_DES: CUP_nM1025_M2_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1025_M2_DF_USMC_DES: CUP_nM1025_M2_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1025_M240_USMC_DES: CUP_nM1025_M240_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1025_M240_DF_USMC_DES: CUP_nM1025_M240_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1025_Mk19_USMC_DES: CUP_nM1025_Mk19_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1025_Mk19_DF_USMC_DES: CUP_nM1025_Mk19_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1025_Unarmed_USMC_DES: CUP_nM1025_Unarmed_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1025_Unarmed_DF_USMC_DES: CUP_nM1025_Unarmed_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1025_SOV_M2_USMC_DES: CUP_nM1025_SOV_M2_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1025_SOV_Mk19_USMC_DES: CUP_nM1025_SOV_Mk19_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1036_TOW_USMC_DES: CUP_nM1036_TOW_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1036_TOW_DF_USMC_DES: CUP_nM1036_TOW_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1037sc_USMC_DES: CUP_nM1037sc_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1037sc_DF_USMC_DES: CUP_nM1037sc_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1038_USMC_DES: CUP_nM1038_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1038_DF_USMC_DES: CUP_nM1038_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1038_4s_USMC_DES: CUP_nM1038_4s_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1038_4s_DF_USMC_DES: CUP_nM1038_4s_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1038_Ammo_DF_USMC_DES: CUP_nM1038_Ammo_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1038_Repair_USMC_DES: CUP_nM1038_Repair_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1038_Repair_DF_USMC_DES: CUP_nM1038_Repair_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1151_mctags_m2_USMC_DES: CUP_ECVHMMWV_ogpk_m2_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1151_mctags_m2_DF_USMC_DES: CUP_ECVHMMWV_ogpk_m2_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1151_mctags_m240_USMC_DES: CUP_ECVHMMWV_ogpk_m240_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1151_mctags_mk19_USMC_DES: CUP_ECVHMMWV_ogpk_mk19_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1151_mctags_m240_DF_USMC_DES: CUP_ECVHMMWV_ogpk_m240_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1151_mctags_mk19_DF_USMC_DES: CUP_ECVHMMWV_ogpk_mk19_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM1151_Unarmed_DF_USMC_DES: CUP_ECVHMMWV_Unarmed_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1151_M2_DSRT_USMC: CUP_M1151_M2_BASE {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1151_Mk19_DSRT_USMC: CUP_M1151_Mk19_BASE {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1151_DSRT_USMC: CUP_M1151_Unarmed_BASE {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1152_DSRT_USMC: CUP_M1152_BASE {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1165_GMV_DSRT_USMC: CUP_M1165_GMV_BASE {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1167_DSRT_USMC: CUP_M1167_BASE {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_nM997_DF_USMC_DES: CUP_nM997_amb_DF_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_RG31_Mk19_USMC: CUP_RG31_Mk19 {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_RG31_M2_USMC: CUP_RG31_M2 {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_RG31_M2_GC_USMC: CUP_RG31_M2_GC {
    MACRO_HIDE_VEHICLE;
};

// Drones
class CUP_B_Seafox_USV_USMC: CUP_B_Seafox_USMC {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_USMC_DYN_MQ9: CUP_MQ9_Dyn_Base {
    MACRO_HIDE_VEHICLE;
};

// Helicopters
class CUP_B_UH1Y_Gunship_Dynamic_USMC: CUP_B_UH1Y_GUNSHIP_USMC {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_AH1Z_Dynamic_USMC: CUP_AH1Z_Dynamic_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_CH53E_USMC: CUP_CH53E_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_CH53E_VIV_USMC: CUP_CH53E_VIV_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_MH60L_DAP_2x_USN: CUP_UH60S_Dap_2x_Dynamic_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_MH60L_DAP_4x_USN: CUP_UH60S_Dap_4x_Dynamic_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_MH60S_USMC: CUP_MH60S_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_UH60S_USN: CUP_Uh60S_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_MH60S_Unarmed_USN: CUP_UH60_Unarmed_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_MH60S_Unarmed_FFV_USN: CUP_MH60S_Unarmed_FFV_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_UH1Y_UNA_USMC: CUP_B_UH1Y_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_UH1Y_MEV_USMC: CUP_B_UH1Y_UNA_USMC {
    MACRO_HIDE_VEHICLE;
};

// Planes
class CUP_B_AV8B_DYN_USMC: CUP_AV8B_DYN_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_C130J_USMC: CUP_C130J_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_C130J_Cargo_USMC: CUP_C130J_VIV_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_F35B_USMC: CUP_F35B_dynamic_base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_F35B_Stealth_USMC: CUP_F35B_dynamic_stealth_base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_MV22_USMC: Plane_Base_F {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_MV22_USMC_RAMPGUN: CUP_B_MV22_USMC {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_MV22_VIV_USMC: CUP_B_MV22_USMC {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_P8Poseidon_USN: CUP_Ambient_B737_Base {
    MACRO_HIDE_VEHICLE;
};

// Tanks
class CUP_B_M1A1FEP_Desert_USMC: CUP_M1Abrams_M1A1FEP_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1A1FEP_TUSK_Desert_USMC: CUP_M1Abrams_M1A1FEP_F_TUSK_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1A1EP_TUSK_OD_USMC: CUP_M1Abrams_M1A1FEP_F_TUSK_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1A1FEP_OD_USMC: CUP_M1Abrams_M1A1FEP_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1A1FEP_Woodland_USMC: CUP_M1Abrams_M1A1FEP_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M1A1EP_TUSK_Woodland_USMC: CUP_M1Abrams_M1A1FEP_F_TUSK_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M60A3_USMC: CUP_M60A3_Base {
    MACRO_HIDE_VEHICLE;
};
class CUP_B_M60A3_TTS_USMC: CUP_M60A3_TTS_Base {
    MACRO_HIDE_VEHICLE;
};

// Turrets
class CUP_UH1Y_StaticWeapon_Wreck: StaticWeapon {
    MACRO_HIDE_VEHICLE;
};
