name = "GT Armory"
prefix = "tacgt"
mainprefix = "x"
author = "Theseus Incorporated"

[files]
include = [
    "mod.cpp",
    "README.md",
    "tacgt_logo_128.paa",
    "tacgt_logo_64.paa"
]

[version]
git_hash = 0

[hemtt.release]
folder = "gt_armory"

[hemtt.launch.default]
workshop = [
    "450814997", # CBA
    "463939057", # ACE3
    "646999497", # Theseus Services
]

[hemtt.launch.zen]
extends = "default"
workshop = [
    "1779063631", # Zeus Enhanced
]

[hemtt.launch.adt]
extends = "default"
workshop = [
    "2369477168", # ADT
]

[hemtt.launch.ws]
extends = "default"
dlc = [
    "ws",
]

[hemtt.launch.rf]
extends = "default"
dlc = [
    "rf",
]

[hemtt.launch.aegis]
extends = "default"
workshop = [
    "2538332070", # Aegis - Development
]

[hemtt.launch.atlas]
extends = "default"
workshop = [
    "2538339575", # Atlas - Development
]
