    class CLASS(Lootbox_LMG): CLASS(Replacement_Base) {
        picture = QPATHTOF(ui\lootbox_lmg_ca.paa);
        displayName = CSTRING(Lootbox_LMG_Name);
        tacgt_lootbox_list[] = {
            "LMG_03_F",
            "arifle_SPAR_02_blk_F",
            "arifle_SPAR_02_khk_F",
            "arifle_SPAR_02_snd_F",
            "arifle_MX_SW_khk_F",
            "arifle_MX_SW_F",
            "arifle_MX_SW_Black_F",
            "arifle_CTARS_blk_F",
            "LMG_Mk200_F",
            "LMG_Mk200_black_F",
            "arifle_RPK12_F",
            "arifle_RPK12_arid_F",
            "arifle_RPK12_lush_F",
            "tacgt_lmg_lamg",
            "CUP_arifle_L86A2",
            "CUP_lmg_m249_pip1",
            "CUP_lmg_m249_pip3",
            "CUP_lmg_m249_SQuantoon",
            "CUP_arifle_HK_M27",
            "CUP_arifle_HK_M27_VFG",
            "CUP_lmg_M60E4",
            "CUP_lmg_Mk48_nohg",
            "CUP_lmg_Mk48_nohg_des",
            "CUP_lmg_Mk48_nohg_od",
            "CUP_lmg_Mk48_nohg_tan",
            "CUP_lmg_Mk48_nohg_wdl",
            "CUP_lmg_PKMN",
            "CUP_lmg_Pecheneg_top_rail_B50_vfg",
            "CUP_arifle_RPK74",
            "CUP_arifle_RPK74_top_rail",
            "CUP_arifle_RPK74_45",
            "CUP_arifle_RPK74_45_top_rail",
            "CUP_arifle_RPK74M",
            "CUP_arifle_RPK74M_top_rail",
            "CUP_arifle_RPK74M_railed",
            "hlc_lmg_mk46",
            "hlc_lmg_mk48",
            "hlc_lmg_mk48mod1"
        };
    };
