    class CLASS(Lootbox_Marksman): tac_supplies_replacementBox {
        picture = QPATHTOF(ui\lootbox_marksman_ca.paa);
        displayName = CSTRING(Lootbox_Marksman_Name);
        tac_supplies_possibleItems[] = {
            "arifle_SPAR_03_blk_F",
            "arifle_SPAR_03_khk_F",
            "arifle_SPAR_03_snd_F",
            "srifle_EBR_F",
            "tacs_EBR_Black_F",
            "arifle_MSBS65_Mark_F",
            "arifle_MSBS65_Mark_black_F",
            "arifle_MSBS65_Mark_camo_F",
            "arifle_MSBS65_Mark_sand_F",
            "arifle_MXM_F",
            "arifle_MXM_Black_F",
            "arifle_MXM_khk_F",
            "srifle_DMR_02_F",
            "srifle_DMR_07_blk_F",
            "srifle_DMR_07_ghex_F",
            "srifle_DMR_07_hex_F",
            "srifle_DMR_03_F",
            "srifle_DMR_03_multicam_F",
            "srifle_DMR_03_khaki_F",
            "srifle_DMR_03_tan_F",
            "srifle_DMR_03_woodland_F",
            "CUP_arifle_Mk16_SV_black",
            "CUP_arifle_Mk16_SV",
            "CUP_arifle_Mk20",
            "CUP_arifle_Mk20_black",
            "CUP_srifle_L129A1",
            "CUP_srifle_L129A1_HG",
            "CUP_arifle_HK417_20",
            "CUP_srifle_M110_black",
            "CUP_srifle_M14_DMR",
            "CUP_srifle_Mk12SPR",
            "CUP_arifle_DSA_SA58_DMR",
            "CUP_srifle_SVD",
            "CUP_srifle_SVD_top_rail",
            "hlc_rifle_SAMR2",
            "hlc_rifle_SG550Sniper_RIS"
        };
    };
